### ISSUE TITLE
Set up continuous integration with CircleCI

### ISSUE THREAD

**Issue by Gaurav0** [GreatWizard/ember-circleci#3]
I think PRs should be tested on this addon with CircleCI so that we know users will have this working.

**Comment by GreatWizard** [comment]
This is the case, see https://circleci.com/gh/GreatWizard/ember-circleci/
If you fork the repository, you can"t have my CI setup launch on your fork.

You need to make a PR on this repository to start the CI

**Comment by Gaurav0** [comment]
https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories

**Comment by GreatWizard** [comment]
You right, it's activated :)
